branches:
  only:
  - master
env:
 
  global:
  - secure: BeurG3Cuee3lNmRclebXKHAAkPhhXgzNOUpOMl1INLnEtXQ52ZIzyDzeiUA32AIvi3/ICOEOSpiDxI1XWIW9KmJPDjtlImAA6VMe5DLHAwBQYqve/T4NH+jPVyShOoc4RCeevpzThDkzFY08CaamXrnDCqzyItCD/OndJgoZ7Ko=
  - secure: CIK/eqhPHiSVUoOHzm2Rxl7Rg+TozfWD5XkD91uZd1hXN3AlKUae0/3lqRVnyxILPY286TTCuLa84LSvWmirvfximNsRxU4d8TzX3bMM2PlNQYdQoczy+TySiM250d5aq+MP8Lg8joEfsOXJDDvoYEZxvkEzvSJoVWh48QSoDtI=
  - ELM_HOME="./elm-home"
install: 
- wget http://JoeyEremondi.github.io/elm-travis-cache/elm
- wget http://JoeyEremondi.github.io/elm-travis-cache/elm-get
- wget http://JoeyEremondi.github.io/elm-travis-cache/elm_home.tar.gz
- chmod +x ./elm
- chmod +x ./elm-get
- tar -xzf elm_home.tar.gz ./
- ./elm-get install johnpmayer/elm-linear-algebra
- ./elm-get install johnpmayer/elm-webgl
before_script:
- cd build
- git checkout gh-pages
- git pull
- cd ..
script: 
 - ./elm --make --set-runtime="http://eremondi.com/elm-travis-cache/elm-runtime.js" ObjTest.elm 
 - yes | cp ./*.jpg ./build
 - yes | cp ./*.png ./build
after_script:
- cd build
- git status
- git config --global user.email "joey@eremondi.com"
- git config --global user.name "JoeyEremondi"
- git add --all
- git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
- git push "https://""$GH_KEY""@github.com/JoeyEremondi/ElmObjParser.git"  gh-pages
  >/dev/null 2>&1
- cd ..
